# This message contains documentation data about a topic in a node

# The internal name of the topic
string name

# The external, global name of the topic
string resolved_name

# A human readable description of the topic and how to use it
string description

# Used to group related components
string group

# The name of the message type
string message_type

# If the topic is being advertised, otherwise it is being subscribed to
bool advertised
